# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1528994528);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1528994648);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1528997768);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1528994408);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1528994888);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1528994288);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1528995008);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1528994768);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1528994137);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 62);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"18696\":1528994148336,\"18699\":1528994148336,\"18701\":1528994148336,\"18704\":1528997978190}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{b90fdbe3-cac8-4236-9ecd-8bbceb6aed93}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1528956000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1528994149);
user_pref("browser.onboarding.notification.prompt-count", 3);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1528997800486");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1528999591486");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1528997745598");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1529001345598");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1528994143");
user_pref("browser.slowStartup.averageTime", 2545);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180406121424");
user_pref("browser.startup.homepage_override.mstone", "59.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1528994141754");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "59.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1528994528);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "59.0.2");
user_pref("extensions.lastPlatformVersion", "59.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "90b1156b-fbc1-4f99-b506-6636b42f9d37");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"37a0705e-21a5-433f-82bd-8f0964be4615\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1528994330);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1528994171);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180406121424");
user_pref("media.gmp-manager.lastCheck", 1528994171);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1528994330);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1528918905);
user_pref("services.blocklist.clock_skew_seconds", 75742);
user_pref("services.blocklist.gfx.checked", 1528918905);
user_pref("services.blocklist.last_etag", "\"1528408770328\"");
user_pref("services.blocklist.last_update_seconds", 1528918905);
user_pref("services.blocklist.onecrl.checked", 1528918905);
user_pref("services.blocklist.pinning.checked", 1528918905);
user_pref("services.blocklist.plugins.checked", 1528918905);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1528994330);
user_pref("toolkit.startup.last_success", 1528994136);
user_pref("toolkit.telemetry.cachedClientID", "794e358e-6a0e-4c10-9469-8652ed8f0994");
user_pref("toolkit.telemetry.previousBuildID", "20180406121424");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
